DROP DATABASE closets_db;
CREATE DATABASE closets_db;
USE closets_db;

CREATE TABLE items (
	id INT(100) AUTO_INCREMENT NOT NULL,
	name VARCHAR(300) NOT NULL,
	img_url VARCHAR(1000),
	userId INT(100) NOT NULL,
	description VARCHAR(1000),
	categoryId INT(100) NOT NULL,
	subcategory VARCHAR(1000),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	-- createdAt VARCHAR(100) NOT NULL,
	-- updatedAt VARCHAR(100) NOT NULL,
	tags VARCHAR(1000),
	PRIMARY KEY (id)
);

CREATE TABLE users (
	id INT(100) AUTO_INCREMENT NOT NULL,
	name VARCHAR(300) NOT NULL,
	img_url VARCHAR(1000),
	description VARCHAR(1000) NOT NULL,
	auth_method VARCHAR(100),
	auth_id INT(100),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE categories (
	id INT(100) AUTO_INCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE robabilities (
	id INT(100) AUTO_INCREMENT NOT NULL,
	userId INT(100),
	voter_id INT(100),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	score INT(10),
    PRIMARY KEY (id)
);